import type { ForgeUIPlugin } from "@forgeui/cli";

/**
 * Example ForgeUI plugin:
 * - Adds a short banner comment to the top of generated tokens.css
 * - Demonstrates reading plugin options from `cfg.plugins[].options`
 */
const plugin: ForgeUIPlugin = {
  name: "example-banner",
  hooks: {
    afterGenerate(ctx) {
      const banner = String((plugin as any).options?.banner ?? "Generated by ForgeUI (example plugin)");
      if (!ctx.outputs?.css) return;
      ctx.outputs.css = `/* ${banner} */\n` + ctx.outputs.css;
    }
  }
};

export default plugin;
