import type { ForgeUIPlugin } from "../plugins.js";

/**
 * Builtin plugin: banner
 *
 * Options:
 * - banner: string (comment text)
 * - file: string (output key/filename to prepend to, default: "tokens.css")
 */
export function builtinBannerPlugin(): ForgeUIPlugin {
  const plugin: ForgeUIPlugin = {
    name: "builtin:banner",
    hooks: {
      afterGenerate(ctx) {
        const banner = String((ctx.pluginOptions as any)?.banner ?? "Generated by ForgeUI");
        const file = String((ctx.pluginOptions as any)?.file ?? "tokens.css");
        const prev = ctx.outputs?.[file];
        if (!prev) return;
        ctx.outputs[file] = `/* ${banner} */\n` + prev;
      }
    },
    optionsSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        banner: { type: "string" },
        file: { type: "string" }
      }
    }
  };

  return plugin;
}
