/* Generated by ForgeUI. Do not edit by hand. */

/*
Tailwind v4 usage (CSS-first):

  // in your app CSS
  @import "tailwindcss";
  @config "./forgeui/forgeui.preset.ts";

  // ensure this is loaded too
  @import "./forgeui/tokens.css";
*/

import theme from "./forgeui.theme";

const preset = {
  darkMode: [
  'class',
  '[data-theme=\'dark\']',
],
  theme: {
    extend: theme,
  },
} as const;

export default preset;
