/* Generated by ForgeUI. Do not edit by hand. */

/*
Tailwind v3 usage:

  // tailwind.config.js (or .cjs)
  module.exports = {
    presets: [require("./forgeui/forgeui.preset.cjs")],
  };

  // ensure this is loaded too (your app CSS)
  @import "./forgeui/tokens.css";
*/

const theme = require("./forgeui.theme");

const preset = {
  darkMode: [
  'class',
  '[data-theme=\'dark\']',
],
  theme: {
    extend: theme,
  },
} as const;

module.exports = preset;
