/* Generated by ForgeUI. Do not edit by hand. */

/*
Tailwind v4 usage (CSS-first):

  // in your app CSS
  @import "tailwindcss";
  @config "./forgeui/forgeui.preset.ts";

  // ensure this is loaded too
  @import "./forgeui/tokens.css";
*/

const preset = {
  darkMode: [
    'class',
    '[data-theme=\'dark\']',
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          default: 'rgb(var(--core-color-bg-default) / <alpha-value>)',
        },
        fg: {
          default: 'rgb(var(--core-color-fg-default) / <alpha-value>)',
        },
        brand: {
          '500': 'rgb(var(--core-color-brand-500) / <alpha-value>)',
        },
      },
      spacing: {
        '4': '16px',
        '8': '32px',
      },
      borderRadius: {
        md: '10px',
      },
      boxShadow: {},
      borderColor: {},
      borderWidth: {},
      borderStyle: {},
      fontFamily: {},
      fontSize: {},
      fontWeight: {},
      letterSpacing: {},
      lineHeight: {},
    },
  },
} as const;

export default preset;
