/* Generated by ForgeUI. Do not edit by hand. */

/*
Tailwind v3 usage:

  // tailwind.config.js (or .cjs)
  module.exports = {
    presets: [require("./forgeui/forgeui.preset.cjs")],
  };

  // ensure this is loaded too (your app CSS)
  @import "./forgeui/tokens.css";
*/

const preset = {
  darkMode: [
    'class',
    '[data-theme=\'dark\']',
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          default: 'rgb(var(--core-color-bg-default) / <alpha-value>)',
        },
        fg: {
          default: 'rgb(var(--core-color-fg-default) / <alpha-value>)',
        },
        brand: {
          '500': 'rgb(var(--core-color-brand-500) / <alpha-value>)',
        },
      },
      spacing: {
        '4': '16px',
        '8': '32px',
      },
      borderRadius: {
        md: '10px',
      },
      boxShadow: {},
      borderColor: {},
      borderWidth: {},
      borderStyle: {},
      backgroundImage: {},
      fontFamily: {},
      fontSize: {},
      fontWeight: {},
      letterSpacing: {},
      lineHeight: {},
    },
  },
} as const;

module.exports = preset;
