/* Generated by ForgeUI. Do not edit by hand. */

const theme = {
  colors: {
    bg: {
      default: 'rgb(var(--core-color-bg-default) / <alpha-value>)',
    },
    fg: {
      default: 'rgb(var(--core-color-fg-default) / <alpha-value>)',
    },
    brand: {
      '500': 'rgb(var(--core-color-brand-500) / <alpha-value>)',
    },
  },
  spacing: {
    '4': '16px',
    '8': '32px',
  },
  borderRadius: {
    md: '10px',
  },
  boxShadow: {},
  borderColor: {},
  borderWidth: {},
  borderStyle: {},
  fontFamily: {},
  fontSize: {},
  fontWeight: {},
  letterSpacing: {},
  lineHeight: {},
} as const;

export default theme;
