import { formatTs } from "./format.js";

export function generateTailwindThemeFragment(themeExtend: any): string {
  return `/* Generated by ForgeUI. Do not edit by hand. */\n\nconst theme = ${formatTs(themeExtend)} as const;\n\nexport default theme;\n`;
}
