import path from "node:path";
import type { ForgeUIConfig, Theme, TokensStudioDoc } from "./types.js";
import { flattenSetTokens, getThemes, listEnabledSetsForTheme, resolveTokenValue } from "./tokens.js";
import { slugify, toKebab } from "./utils.js";

function themeSelector(cfg: ForgeUIConfig, theme: Theme): string {
  const name = theme.name;
  const explicit = cfg.themes.selectorByTheme?.[name];
  if (explicit) return explicit;
  if (name === cfg.themes.rootTheme) return ":root";
  return `[data-theme=\"${slugify(name)}\"]`;
}

function varNameFromTokenPath(tokenPath: string[]): string {
  // collision-proof, fully qualified
  return `--${toKebab(tokenPath)}`;
}

function hexToRgbTriplet(hex: string): string | null {
  const h = hex.trim();
  const m = h.match(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/);
  if (!m) return null;
  let x = m[1];
  if (x.length === 3) x = x.split("").map((c) => c + c).join("");
  const r = parseInt(x.slice(0, 2), 16);
  const g = parseInt(x.slice(2, 4), 16);
  const b = parseInt(x.slice(4, 6), 16);
  return `${r} ${g} ${b}`;
}

export function generateTokensCss(doc: TokensStudioDoc, cfg: ForgeUIConfig): string {
  const themes = getThemes(doc);

  const blocks: string[] = [];
  for (const theme of themes) {
    const enabledSets = listEnabledSetsForTheme(theme);
    const selector = themeSelector(cfg, theme);

    const lines: string[] = [];
    for (const setName of enabledSets) {
      const setObj = (doc as any)[setName];
      const flat = flattenSetTokens(setObj, [setName]);
      for (const t of flat) {
        const resolved = resolveTokenValue(doc, t.leaf, theme.name);
        const varName = varNameFromTokenPath(t.path);

        if (t.leaf.$type === "color" && typeof resolved === "string") {
          const rgb = hexToRgbTriplet(resolved);
          lines.push(`  ${varName}: ${rgb ?? resolved};`);
        } else if (t.leaf.$type === "shadow") {
          // Minimal: stringify for now; Tailwind boxShadow will use same string.
          lines.push(`  ${varName}: ${JSON.stringify(resolved)};`);
        } else {
          lines.push(`  ${varName}: ${String(resolved)};`);
        }
      }
    }

    blocks.push(`${selector} {\n${lines.sort().join("\n")}\n}`);

    // Optional `.dark` mirror for dark theme
    if (cfg.css.alsoEmitClassDark && theme.name === cfg.tailwind.darkThemeName) {
      blocks.push(`.dark {\n${lines.sort().join("\n")}\n}`);
    }
  }

  return `/* Generated by ForgeUI. Do not edit by hand. */\n\n${blocks.join("\n\n")}\n`;
}

function tokenPathToTailwindColorKey(tokenPath: string[]): string[] {
  // Expect [setName, 'color', ...]
  const idx = tokenPath.indexOf("color");
  if (idx === -1) return [];
  return tokenPath.slice(idx + 1);
}

function tailwindColorValue(varName: string): string {
  // We store colors as `r g b` triplets in vars when possible.
  return `rgb(var(${varName}) / <alpha-value>)`;
}

export function generateTailwindPreset(doc: TokensStudioDoc, cfg: ForgeUIConfig): string {
  const rootTheme = cfg.themes.rootTheme;
  const root = getThemes(doc).find((t) => t.name === rootTheme);
  if (!root) throw new Error(`Root theme not found: ${rootTheme}`);

  const enabledSets = listEnabledSetsForTheme(root);

  const colors: any = {};

  for (const setName of enabledSets) {
    const flat = flattenSetTokens((doc as any)[setName], [setName]);
    for (const t of flat) {
      if (t.leaf.$type !== "color") continue;
      const keyPath = tokenPathToTailwindColorKey(t.path);
      if (keyPath.length === 0) continue;
      const vname = `--${toKebab(t.path)}`;

      // Build nested object
      let cur = colors;
      for (let i = 0; i < keyPath.length; i++) {
        const k = keyPath[i];
        const last = i === keyPath.length - 1;
        if (last) {
          cur[k] = tailwindColorValue(vname);
        } else {
          cur[k] ??= {};
          cur = cur[k];
        }
      }
    }
  }

  const preset = {
    darkMode: ["class", "[data-theme='dark']"],
    theme: {
      extend: {
        colors
      }
    }
  };

  return `/* Generated by ForgeUI. Do not edit by hand. */\n\nconst preset = ${JSON.stringify(
    preset,
    null,
    2
  )} as const;\n\nexport default preset;\n`;
}

export function outPath(cfg: ForgeUIConfig, file: string): string {
  return path.resolve(process.cwd(), cfg.outDir, file);
}
